schedules:
  # nightly builds to populate caches
  - cron: "3 0 * * Mon"
    displayName: Weekly midnight build
    branches:
      include:
      - main
    always: true
  - cron: "3 0 * * Tue-Sat,Sun"
    displayName: Daily midnight build
    branches:
      include:
      - main

extends:
  template: .azure-pipelines/azure-pipelines.yml
