from typing import Any

# MinusY: KappaDirection
# MinusZ: KappaDirection
# Omega: KappaScanAxis
# Phi: KappaScanAxis
# PlusY: KappaDirection
# PlusZ: KappaDirection

# class Beam(BeamBase):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def from_dict(self, *args, **kwargs) -> Any: ...
#     def to_dict(self) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __getstate__(boost) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setstate__(self, state) -> Any: ...

# class BeamBase:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def get_divergence(self) -> Any: ...
#     def get_flux(self) -> Any: ...
#     def get_num_scan_points(self) -> Any: ...
#     def get_polarization_fraction(self) -> Any: ...
#     def get_polarization_normal(self) -> Any: ...
#     def get_s0(self) -> Any: ...
#     def get_s0_at_scan_point(self, unsignedlong) -> Any: ...
#     def get_s0_at_scan_points(self) -> Any: ...
#     def get_sample_to_source_direction(self) -> Any: ...
#     def get_sigma_divergence(self) -> Any: ...
#     def get_transmission(self) -> Any: ...
#     def get_unit_s0(self) -> Any: ...
#     def get_wavelength(self) -> Any: ...
#     def is_similar_to(self, *args, **kwargs) -> Any: ...
#     def reset_scan_points(self) -> Any: ...
#     def rotate_around_origin(self, *args, **kwargs) -> Any: ...
#     def set_direction(self, scitbx) -> Any: ...
#     def set_divergence(self, *args, **kwargs) -> Any: ...
#     def set_flux(self, double) -> Any: ...
#     def set_polarization_fraction(self, double) -> Any: ...
#     def set_polarization_normal(self, scitbx) -> Any: ...
#     def set_s0(self, scitbx) -> Any: ...
#     @overload
#     def set_s0_at_scan_points(self, boost) -> Any: ...
#     @overload
#     def set_s0_at_scan_points(self, boost) -> Any: ...
#     def set_sigma_divergence(self, *args, **kwargs) -> Any: ...
#     def set_transmission(self, double) -> Any: ...
#     def set_unit_s0(self, scitbx) -> Any: ...
#     def set_wavelength(self, double) -> Any: ...
#     def __eq__(self, other) -> Any: ...
#     def __ne__(self, other) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     @property
#     def num_scan_points(self) -> Any: ...

# class Crystal(CrystalBase):
#     def __init__(boost, scitbx, cctbx) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __getstate__(boost) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setstate__(self, state) -> Any: ...

# class CrystalBase:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def change_basis(self, cctbx) -> Any: ...
#     def get_A(self) -> Any: ...
#     def get_A_at_scan_point(self, unsignedlong) -> Any: ...
#     def get_B(self) -> Any: ...
#     def get_B_at_scan_point(self, unsignedlong) -> Any: ...
#     def get_B_covariance(self) -> Any: ...
#     def get_B_covariance_at_scan_point(self, unsignedlong) -> Any: ...
#     def get_B_covariance_at_scan_points(self) -> Any: ...
#     def get_U(self) -> Any: ...
#     def get_U_at_scan_point(self, unsignedlong) -> Any: ...
#     def get_cell_parameter_sd(self) -> Any: ...
#     def get_cell_parameter_sd_at_scan_point(self, unsignedlong) -> Any: ...
#     def get_cell_volume_sd(self) -> Any: ...
#     def get_num_scan_points(self) -> Any: ...
#     def get_real_space_vectors(self) -> Any: ...
#     def get_recalculated_cell_parameter_sd(self) -> Any: ...
#     def get_recalculated_cell_volume_sd(self) -> Any: ...
#     def get_recalculated_unit_cell(self) -> Any: ...
#     def get_space_group(self) -> Any: ...
#     def get_unit_cell(self) -> Any: ...
#     def get_unit_cell_at_scan_point(self, unsignedlong) -> Any: ...
#     def is_similar_to(self, *args, **kwargs) -> Any: ...
#     def reset_scan_points(self) -> Any: ...
#     def reset_unit_cell_errors(self) -> Any: ...
#     def rotate_around_origin(self, *args, **kwargs) -> Any: ...
#     def set_A(self, scitbx) -> Any: ...
#     @overload
#     def set_A_at_scan_points(self, boost) -> Any: ...
#     @overload
#     def set_A_at_scan_points(self, boost) -> Any: ...
#     def set_B(self, scitbx) -> Any: ...
#     def set_B_covariance(self, boost) -> Any: ...
#     def set_B_covariance_at_scan_points(self, *args, **kwargs) -> Any: ...
#     def set_U(self, scitbx) -> Any: ...
#     def set_recalculated_cell_parameter_sd(self, *args, **kwargs) -> Any: ...
#     def set_recalculated_cell_volume_sd(self, double) -> Any: ...
#     def set_recalculated_unit_cell(self, cctbx) -> Any: ...
#     def set_space_group(self, cctbx) -> Any: ...
#     def set_unit_cell(self, cctbx) -> Any: ...
#     def update(self, *args, **kwargs) -> Any: ...
#     def update_B(self) -> Any: ...
#     def __eq__(self, other) -> Any: ...
#     def __ne__(self, other) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     @property
#     def num_scan_points(self) -> Any: ...

class Detector:
    def __init__(self, *args, **kwargs) -> None: ...
    def add_group(self) -> Any: ...
    def add_panel(self) -> Any: ...
    def from_dict(self, *args, **kwargs) -> Any: ...
    def get_max_inscribed_resolution(self, scitbx) -> Any: ...
    def get_max_resolution(self, scitbx) -> Any: ...
    def get_names(self) -> Any: ...
    def get_panel_intersection(self, scitbx) -> Any: ...
    def get_ray_intersection(self, scitbx) -> Any: ...
    def has_projection_2d(self) -> Any: ...
    def hierarchy(self) -> DetectorNode: ...
    def is_similar_to(self, *args, **kwargs) -> Any: ...
    def rotate_around_origin(self, *args, **kwargs) -> Any: ...
    def to_dict(self) -> Any: ...
    def __copy__(self, boost) -> Any: ...
    def __deepcopy__(self, boost) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __getitem__(self, unsignedlong) -> Any: ...
    def __getstate__(boost) -> Any: ...
    def __iter__(boost) -> Any: ...
    def __len__(self) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setitem__(self, index, object) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Experiment:
    beam: Any
    crystal: Any
    detector: Any
    goniometer: Any
    identifier: Any
    imageset: Any
    profile: Any
    scaling_model: Any
    scan: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def is_consistent(self) -> Any: ...
    def is_sequence(self) -> Any: ...
    def is_still(self) -> Any: ...
    def __contains__(self, boost) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __getinitargs__(self) -> Any: ...
    def __reduce__(self) -> Any: ...

class ExperimentList:
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs) -> Any: ...
    def clear(self) -> Any: ...
    def empty(self) -> Any: ...
    def extend(self, *args, **kwargs) -> Any: ...
    def find(self, *args, **kwargs) -> Any: ...
    def identifiers(self) -> Any: ...
    def indices(self, boost) -> Any: ...
    def is_consistent(self) -> Any: ...
    def remove_on_experiment_identifiers(self, boost) -> Any: ...
    def replace(self, *args, **kwargs) -> Any: ...
    def select_on_experiment_identifiers(self, boost) -> Any: ...
    def where(self) -> Any: ...
    def __contains__(self, boost) -> bool: ...
    def __delitem__(self, int) -> Any: ...
    def __getinitargs__(self) -> Any: ...
    def __getitem__(self, index: int) -> Experiment: ...
    def __iter__(boost) -> Any: ...
    def __len__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setitem__(self, index, object) -> Any: ...

# class Goniometer(GoniometerBase):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def from_dict(self, *args, **kwargs) -> Any: ...
#     def get_fixed_rotation(self) -> Any: ...
#     def get_num_scan_points(self) -> Any: ...
#     def get_rotation_axis(self) -> Any: ...
#     def get_rotation_axis_datum(self) -> Any: ...
#     def get_setting_rotation(self) -> Any: ...
#     def get_setting_rotation_at_scan_point(self, unsignedlong) -> Any: ...
#     def get_setting_rotation_at_scan_points(self) -> Any: ...
#     def is_similar_to(self, *args, **kwargs) -> Any: ...
#     def reset_scan_points(self) -> Any: ...
#     def rotate_around_origin(self, *args, **kwargs) -> Any: ...
#     def set_fixed_rotation(self, scitbx) -> Any: ...
#     def set_rotation_axis(self, scitbx) -> Any: ...
#     def set_rotation_axis_datum(self, scitbx) -> Any: ...
#     def set_setting_rotation(self, scitbx) -> Any: ...
#     @overload
#     def set_setting_rotation_at_scan_points(self, boost) -> Any: ...
#     @overload
#     def set_setting_rotation_at_scan_points(self, boost) -> Any: ...
#     def to_dict(self) -> Any: ...
#     def __eq__(self, other) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __getstate__(boost) -> Any: ...
#     def __ne__(self, other) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setstate__(self, state) -> Any: ...
#     @property
#     def num_scan_points(self) -> Any: ...

# class GoniometerBase:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def __reduce__(self) -> Any: ...

# class KappaDirection(Boost.Python.enum):
#     MinusY: ClassVar[KappaDirection] = ...
#     MinusZ: ClassVar[KappaDirection] = ...
#     PlusY: ClassVar[KappaDirection] = ...
#     PlusZ: ClassVar[KappaDirection] = ...
#     names: ClassVar[dict] = ...
#     values: ClassVar[dict] = ...

# class KappaGoniometer(Goniometer):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def get_alpha_angle(self) -> Any: ...
#     def get_direction(self) -> Any: ...
#     def get_kappa_angle(self) -> Any: ...
#     def get_kappa_axis(self) -> Any: ...
#     def get_omega_angle(self) -> Any: ...
#     def get_omega_axis(self) -> Any: ...
#     def get_phi_angle(self) -> Any: ...
#     def get_phi_axis(self) -> Any: ...
#     def get_scan_axis(self) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __reduce__(self) -> Any: ...

# class KappaScanAxis(Boost.Python.enum):
#     Omega: ClassVar[KappaScanAxis] = ...
#     Phi: ClassVar[KappaScanAxis] = ...
#     names: ClassVar[dict] = ...
#     values: ClassVar[dict] = ...

# class MosaicCrystalKabsch2010(Crystal):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def get_mosaicity(self) -> Any: ...
#     def is_similar_to(self, *args, **kwargs) -> Any: ...
#     def set_mosaicity(self, *args, **kwargs) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __getstate__(boost) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setstate__(self, state) -> Any: ...

# class MosaicCrystalSauter2014(Crystal):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def get_domain_size_ang(self) -> Any: ...
#     def get_half_mosaicity_deg(self) -> Any: ...
#     def is_similar_to(self, *args, **kwargs) -> Any: ...
#     def set_domain_size_ang(self, double) -> Any: ...
#     def set_half_mosaicity_deg(self, double) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __getstate__(boost) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setstate__(self, state) -> Any: ...

# class MultiAxisGoniometer(Goniometer):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def from_dict(self, *args, **kwargs) -> Any: ...
#     def get_angles(self) -> Any: ...
#     def get_axes(self) -> Any: ...
#     def get_names(self) -> Any: ...
#     def get_scan_axis(self) -> Any: ...
#     def set_angles(self, scitbx) -> Any: ...
#     def set_axes(self, *args, **kwargs) -> Any: ...
#     def to_dict(self) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __getstate__(boost) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setstate__(self, state) -> Any: ...

# class OffsetParallaxCorrectedPxMmStrategy(ParallaxCorrectedPxMmStrategy):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def dx(self) -> Any: ...
#     def dy(self) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __reduce__(self) -> Any: ...

# class OffsetPxMmStrategy(PxMmStrategy):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def dx(self) -> Any: ...
#     def dy(self) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __reduce__(self) -> Any: ...

class Panel:
    def __init__(self, *args, **kwargs) -> None: ...
    def from_dict(self, *args, **kwargs) -> Any: ...
    def get_beam_centre_px(self, scitbx) -> Any: ...
    def get_bidirectional_ray_intersection_px(self, scitbx) -> Any: ...
    def get_cos2_two_theta_array(self, scitbx) -> Any: ...
    def get_gain(self) -> Any: ...
    def get_identifier(self) -> Any: ...
    def get_image_size_mm(self) -> Any: ...
    def get_max_resolution_at_corners(self, scitbx) -> Any: ...
    def get_max_resolution_ellipse(self, scitbx) -> Any: ...
    def get_normal_origin_px(self) -> Any: ...
    def get_pedestal(self) -> Any: ...
    def get_pixel_lab_coord(self, *args, **kwargs) -> Any: ...
    def get_projection_2d(self) -> Any: ...
    def get_px_mm_strategy(self) -> Any: ...
    def get_ray_intersection_px(self, scitbx) -> Any: ...
    def get_resolution_at_pixel(self, *args, **kwargs) -> Any: ...
    def get_trusted_range_mask(self, *args, **kwargs) -> Any: ...
    def get_two_theta_array(self, scitbx) -> Any: ...
    def get_two_theta_at_pixel(self, *args, **kwargs) -> Any: ...
    def get_untrusted_rectangle_mask(self) -> Any: ...
    def is_(self, *args, **kwargs) -> Any: ...
    def is_coord_valid(self, scitbx) -> Any: ...
    def is_coord_valid_mm(self, scitbx) -> Any: ...
    def is_value_in_trusted_range(self, double) -> Any: ...
    def millimeter_to_pixel(self, scitbx) -> Any: ...
    def pixel_to_millimeter(self, scitbx) -> Any: ...
    def rotate_around_origin(self, *args, **kwargs) -> Any: ...
    def set_gain(self, double) -> Any: ...
    def set_identifier(self, *args, **kwargs) -> Any: ...
    def set_pedestal(self, double) -> Any: ...
    def set_projection_2d(self, *args, **kwargs) -> Any: ...
    def set_px_mm_strategy(self, boost) -> Any: ...
    def to_dict(self) -> Any: ...
    def __copy__(self, boost) -> Any: ...
    def __deepcopy__(self, boost) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __getstate__(boost) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class DetectorNode(Panel):
    def __init__(self, *args, **kwargs) -> None: ...
    def add_group(self) -> Any: ...
    def add_panel(self) -> Any: ...
    def children(boost) -> Any: ...
    def empty(self) -> Any: ...
    def index(self) -> Any: ...
    def is_group(self) -> Any: ...
    def is_panel(self) -> Any: ...
    def is_similar_to(self, *args, **kwargs) -> Any: ...
    def parent(self) -> Any: ...
    def root(self) -> Any: ...
    def set_frame(self, *args, **kwargs) -> Any: ...
    def set_local_frame(self, *args, **kwargs) -> Any: ...
    def set_parent_frame(self, *args, **kwargs) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __getitem__(self, unsignedlong) -> Any: ...
    def __iter__(boost) -> Any: ...
    def __len__(self) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...

# class ParallaxCorrectedPxMmStrategy(SimplePxMmStrategy):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def mu(self) -> Any: ...
#     def t0(self) -> Any: ...
#     def __eq__(self, other) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __ne__(self, other) -> Any: ...
#     def __reduce__(self) -> Any: ...

# class PxMmStrategy:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def name(self) -> Any: ...
#     def to_millimeter(self, *args, **kwargs) -> Any: ...
#     def to_pixel(self, *args, **kwargs) -> Any: ...
#     def __eq__(self, other) -> Any: ...
#     def __ne__(self, other) -> Any: ...
#     def __reduce__(self) -> Any: ...

# class Scan(ScanBase):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def append(self, *args, **kwargs) -> Any: ...
#     def from_dict(self, *args, **kwargs) -> Any: ...
#     def get_angle_from_array_index(self, *args, **kwargs) -> Any: ...
#     def get_angle_from_image_index(self, *args, **kwargs) -> Any: ...
#     def get_array_index_from_angle(self, *args, **kwargs) -> Any: ...
#     def get_array_indices_with_angle(self, *args, **kwargs) -> Any: ...
#     def get_array_range(self) -> Any: ...
#     def get_batch_for_array_index(self, int) -> Any: ...
#     def get_batch_for_image_index(self, int) -> Any: ...
#     def get_batch_offset(self) -> Any: ...
#     def get_batch_range(self) -> Any: ...
#     def get_epochs(self) -> Any: ...
#     def get_exposure_times(self) -> Any: ...
#     def get_image_epoch(self, int) -> Any: ...
#     def get_image_index_from_angle(self, *args, **kwargs) -> Any: ...
#     def get_image_indices_with_angle(self, *args, **kwargs) -> Any: ...
#     def get_image_oscillation(self, *args, **kwargs) -> Any: ...
#     def get_image_range(self) -> Any: ...
#     def get_num_images(self) -> Any: ...
#     def get_oscillation(self) -> Any: ...
#     def get_oscillation_range(self) -> Any: ...
#     def get_valid_image_ranges(self, *args, **kwargs) -> Any: ...
#     def is_angle_valid(self, *args, **kwargs) -> Any: ...
#     def is_array_index_valid(self, double) -> Any: ...
#     def is_batch_valid(self, int) -> Any: ...
#     def is_image_index_valid(self, double) -> Any: ...
#     def is_still(self) -> Any: ...
#     def set_batch_offset(self, int) -> Any: ...
#     def set_epochs(self, scitbx) -> Any: ...
#     def set_exposure_times(self, scitbx) -> Any: ...
#     def set_image_range(self, scitbx) -> Any: ...
#     def set_oscillation(self, scitbx) -> Any: ...
#     def set_valid_image_ranges(self, *args, **kwargs) -> Any: ...
#     def swap(self, *args, **kwargs) -> Any: ...
#     def to_dict(self) -> Any: ...
#     def __add__(self, other) -> Any: ...
#     def __copy__(self) -> Any: ...
#     def __deepcopy__(self, boost) -> Any: ...
#     def __eq__(self, other) -> Any: ...
#     def __ge__(self, other) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     @overload
#     def __getitem__(self, int) -> Any: ...
#     @overload
#     def __getitem__(self, boost) -> Any: ...
#     def __gt__(self, other) -> Any: ...
#     def __iadd__(boost, dxtbx) -> Any: ...
#     def __le__(self, other) -> Any: ...
#     def __len__(self) -> Any: ...
#     def __lt__(self, other) -> Any: ...
#     def __ne__(self, other) -> Any: ...
#     def __reduce__(self) -> Any: ...

# class ScanBase:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def __reduce__(self) -> Any: ...

# class SimplePxMmStrategy(PxMmStrategy):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def __getinitargs__(self) -> Any: ...
#     def __reduce__(self) -> Any: ...

# class Spectrum:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def from_dict(self, *args, **kwargs) -> Any: ...
#     def get_emax_eV(self) -> Any: ...
#     def get_emin_eV(self) -> Any: ...
#     def get_energies_eV(self) -> Any: ...
#     def get_weighted_energy_eV(self) -> Any: ...
#     def get_weighted_energy_variance(self) -> Any: ...
#     def get_weighted_wavelength(self) -> Any: ...
#     def get_weights(self) -> Any: ...
#     def to_dict(self) -> Any: ...
#     def __getinitargs__(self) -> Any: ...
#     def __getstate__(boost) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setstate__(self, state) -> Any: ...

# class VirtualPanel(VirtualPanelFrame):
#     def __init__(self, *args, **kwargs) -> None: ...
#     def get_name(self) -> Any: ...
#     def get_type(self) -> Any: ...
#     def set_name(self, *args, **kwargs) -> Any: ...
#     def set_type(self, *args, **kwargs) -> Any: ...
#     def __eq__(self, other) -> Any: ...
#     def __ne__(self, other) -> Any: ...
#     def __reduce__(self) -> Any: ...

# class VirtualPanelFrame:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def get_D_matrix(self) -> Any: ...
#     def get_beam_centre(self, scitbx) -> Any: ...
#     def get_beam_centre_lab(self, scitbx) -> Any: ...
#     def get_bidirectional_ray_intersection(self, scitbx) -> Any: ...
#     def get_d_matrix(self) -> Any: ...
#     def get_directed_distance(self) -> Any: ...
#     def get_distance(self) -> Any: ...
#     def get_fast_axis(self) -> Any: ...
#     def get_lab_coord(self, scitbx) -> Any: ...
#     def get_local_d_matrix(self) -> Any: ...
#     def get_local_fast_axis(self) -> Any: ...
#     def get_local_origin(self) -> Any: ...
#     def get_local_slow_axis(self) -> Any: ...
#     def get_normal(self) -> Any: ...
#     def get_normal_origin(self) -> Any: ...
#     def get_origin(self) -> Any: ...
#     def get_parent_d_matrix(self) -> Any: ...
#     def get_parent_fast_axis(self) -> Any: ...
#     def get_parent_origin(self) -> Any: ...
#     def get_parent_slow_axis(self) -> Any: ...
#     def get_ray_intersection(self, scitbx) -> Any: ...
#     def get_slow_axis(self) -> Any: ...
#     def set_frame(self, *args, **kwargs) -> Any: ...
#     def set_local_frame(self, *args, **kwargs) -> Any: ...
#     def set_parent_frame(self, *args, **kwargs) -> Any: ...
#     def __eq__(self, other) -> Any: ...
#     def __ne__(self, other) -> Any: ...
#     def __reduce__(self) -> Any: ...

# class flex_Beam:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def accessor(self, *args, **kwargs) -> Any: ...
#     def all(self, *args, **kwargs) -> Any: ...
#     def append(self, *args, **kwargs) -> Any: ...
#     def as_1d(self, *args, **kwargs) -> Any: ...
#     def assign(self, *args, **kwargs) -> Any: ...
#     def back(self, *args, **kwargs) -> Any: ...
#     def capacity(self, *args, **kwargs) -> Any: ...
#     def clear(self, *args, **kwargs) -> Any: ...
#     def concatenate(self, *args, **kwargs) -> Any: ...
#     def copy_selected(self, *args, **kwargs) -> Any: ...
#     def deep_copy(self, *args, **kwargs) -> Any: ...
#     def element_size(self, *args, **kwargs) -> Any: ...
#     def extend(self, *args, **kwargs) -> Any: ...
#     def fill(self, *args, **kwargs) -> Any: ...
#     def focus(self, *args, **kwargs) -> Any: ...
#     def focus_size_1d(self, *args, **kwargs) -> Any: ...
#     def front(self, *args, **kwargs) -> Any: ...
#     def id(self, *args, **kwargs) -> Any: ...
#     def insert(self, *args, **kwargs) -> Any: ...
#     def is_0_based(self, *args, **kwargs) -> Any: ...
#     def is_padded(self, *args, **kwargs) -> Any: ...
#     def is_trivial_1d(self, *args, **kwargs) -> Any: ...
#     def last(self, *args, **kwargs) -> Any: ...
#     def nd(self, *args, **kwargs) -> Any: ...
#     def origin(self, *args, **kwargs) -> Any: ...
#     def pop_back(self, *args, **kwargs) -> Any: ...
#     def reserve(self, *args, **kwargs) -> Any: ...
#     def reshape(self, *args, **kwargs) -> Any: ...
#     def resize(self, *args, **kwargs) -> Any: ...
#     def reversed(self, *args, **kwargs) -> Any: ...
#     def select(self, *args, **kwargs) -> Any: ...
#     def set_selected(self, *args, **kwargs) -> Any: ...
#     def shallow_copy(self, *args, **kwargs) -> Any: ...
#     def shift_origin(self, *args, **kwargs) -> Any: ...
#     def size(self, *args, **kwargs) -> Any: ...
#     def __delitem__(self, other) -> Any: ...
#     def __getitem__(self, index) -> Any: ...
#     def __getitem_fgdit__(self, *args, **kwargs) -> Any: ...
#     def __len__(self) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setitem__(self, index, object) -> Any: ...
#     def __sizeof__(self) -> Any: ...

# class flex_Spectrum:
#     def __init__(self, *args, **kwargs) -> None: ...
#     def accessor(self, *args, **kwargs) -> Any: ...
#     def all(self, *args, **kwargs) -> Any: ...
#     def append(self, *args, **kwargs) -> Any: ...
#     def as_1d(self, *args, **kwargs) -> Any: ...
#     def assign(self, *args, **kwargs) -> Any: ...
#     def back(self, *args, **kwargs) -> Any: ...
#     def capacity(self, *args, **kwargs) -> Any: ...
#     def clear(self, *args, **kwargs) -> Any: ...
#     def concatenate(self, *args, **kwargs) -> Any: ...
#     def copy_selected(self, *args, **kwargs) -> Any: ...
#     def deep_copy(self, *args, **kwargs) -> Any: ...
#     def element_size(self, *args, **kwargs) -> Any: ...
#     def extend(self, *args, **kwargs) -> Any: ...
#     def fill(self, *args, **kwargs) -> Any: ...
#     def focus(self, *args, **kwargs) -> Any: ...
#     def focus_size_1d(self, *args, **kwargs) -> Any: ...
#     def front(self, *args, **kwargs) -> Any: ...
#     def id(self, *args, **kwargs) -> Any: ...
#     def insert(self, *args, **kwargs) -> Any: ...
#     def is_0_based(self, *args, **kwargs) -> Any: ...
#     def is_padded(self, *args, **kwargs) -> Any: ...
#     def is_trivial_1d(self, *args, **kwargs) -> Any: ...
#     def last(self, *args, **kwargs) -> Any: ...
#     def nd(self, *args, **kwargs) -> Any: ...
#     def origin(self, *args, **kwargs) -> Any: ...
#     def pop_back(self, *args, **kwargs) -> Any: ...
#     def reserve(self, *args, **kwargs) -> Any: ...
#     def reshape(self, *args, **kwargs) -> Any: ...
#     def resize(self, *args, **kwargs) -> Any: ...
#     def reversed(self, *args, **kwargs) -> Any: ...
#     def select(self, *args, **kwargs) -> Any: ...
#     def set_selected(self, *args, **kwargs) -> Any: ...
#     def shallow_copy(self, *args, **kwargs) -> Any: ...
#     def shift_origin(self, *args, **kwargs) -> Any: ...
#     def size(self, *args, **kwargs) -> Any: ...
#     def __delitem__(self, other) -> Any: ...
#     def __getitem__(self, index) -> Any: ...
#     def __getitem_fgdit__(self, *args, **kwargs) -> Any: ...
#     def __len__(self) -> Any: ...
#     def __reduce__(self) -> Any: ...
#     def __setitem__(self, index, object) -> Any: ...
#     def __sizeof__(self) -> Any: ...

# def get_mod2pi_angles_in_range(*args, **kwargs) -> Any: ...
# def get_range_of_mod2pi_angles(*args, **kwargs) -> Any: ...
# def is_angle_in_range(*args, **kwargs) -> Any: ...
# def parallax_correction(*args, **kwargs) -> Any: ...
# def parallax_correction_inv(*args, **kwargs) -> Any: ...
